title:   'NDS Labs'
author:
  name:  'NDS Labs Team'

author_profile: true

# Use 'remote_theme' when testing locally or using a user's shared theme
#    See https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/
remote_theme: "mmistakes/minimal-mistakes"

# Use 'theme' when using official themes 
#    See https://pages.github.com/themes/
#theme: "minima"

# With jekyll-paginate:
paginate: 5 # amount of posts to show
paginate_path: /page:num/

####################################################################
#                                                                  #
# WARNING: jekyll-paginate-v2 is not yet supported by GitHub pages #
# If hosting on GitHub pages, comment the below section out        #
#                                                                  #
# This will work locally, but GitHub pages may have issues         #
# building or running your site.                                   #
#                                                                  #
####################################################################

# With jekyll-paginate-v2:
#pagination:
#  enabled: true
#  per_page: 3
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
