title:   'NDS Labs'
author:
  name:  'NDS Labs Team'

# Use 'remote_theme' when testing locally
#theme: "mmistakes/minimal-mistakes"

# Use 'theme' when testing on GitHub
remote_theme: "mmistakes/minimal-mistakes"

# Add this as a gem so the GitHub Pages knows to install it before building
plugins:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
